
title: Start Jekyll
email: rh222ki@student.lnu.se
description: >
  Webbsida för examination 1
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:8080"
github_username:  Custerx

# sass options
sass:
    sass_dir: _sass

# collections
collections:
    collection_web: # web projects
        output: true # generate separate files
    collection_offline: # offline projects
        output: true # generate separate files
    collection_lists: # listing pages for web and offline projects
        output: true # generate separate files

# set up default layouts and permalink
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            permalink: "/lego/:year-:month-:day/:title/"
    -
        scope:
            path: ""
            type: "collection_web"
        values:
            layout: "web_project"
    -
        scope:
            path: ""
            type: "collection_offline"
        values:
            layout: "offline_project"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
